mailing/urls.py
from django.urls import path

from mailing import views

app_name = 'mailing'

urlpatterns = [
    path("", views.mailing, name="mailing"),
    path('create_mailing/', views.create_mailing, name='create_mailing'),
    path('update_mailing/<int:mailing_id>', views.update_mailing, name='update_mailing'),
    path('delete_mailing/<int:mailing_id>', views.delete_mailing, name='delete_mailing'),

    path('create/', views.create_mailing_api, name='create_mailing_api'),
    path('delete/<int:mailing_id>', views.delete_mailing_api, name='delete_mailing_api'),
    path('update/<int:mailing_id>', views.update_mailing_api, name='update_mailing_api'),
]

notification_service/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include

from notification_service import views

app_name = 'notification_service'

urlpatterns = [
    path("admin/", admin.site.urls),

    # auth
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path("callback", views.callback, name="callback"),

    path("", views.home, name="home"),
    path('mailing/', include('mailing.urls')),
    path('clients/', include('clients.urls')),
    path('stats/', include('stats.urls')),

]

stats/urls.py
from django.urls import path

from stats import views

app_name = 'stats'

urlpatterns = [
    path('', views.get_common_stats_api, name='get_common_stats_api'),
    path('<int:mailing_id>', views.get_spec_stats_api, name='get_spec_stats_api'),
]

mailing/models.py
import enum
from django.utils import timezone

from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.db.models import CASCADE

from clients.models import Client


class Mailing(models.Model):
    start_time = models.DateTimeField(blank=False, null=False)
    text = models.TextField(blank=False, null=False)
    tags_filter = ArrayField(models.CharField(max_length=50), blank=True, null=True)
    codes_filter = ArrayField(models.IntegerField(), blank=True, null=True)
    end_time = models.DateTimeField(blank=False, null=False)

    @classmethod
    def get_previous_mailings(cls):
        return cls.objects.filter(end_time__lt=timezone.now()).all()

    @classmethod
    def get_current_mailings(cls):
        return cls.objects.filter(start_time__lte=timezone.now(), end_time__gte=timezone.now()).all()

    @classmethod
    def get_future_mailings(cls):
        return cls.objects.filter(start_time__gt=timezone.now()).all()


class MessageStatus(enum.Enum):
    WAITING = enum.auto()  # waiting to be sent for the first time
    SENT = enum.auto()  # successfully sent
    FAILED_WAITING = enum.auto()  # didn't send, but will be sent again
    FAILED = enum.auto()  # didn't send and won't be sent again


class Message(models.Model):
    sent_time = models.DateTimeField(blank=True, null=True)
    status = models.CharField(blank=False, null=False, default=MessageStatus.WAITING, max_length=50)
    mailing = models.ForeignKey(Mailing, on_delete=CASCADE, related_name='messages')
    client = models.ForeignKey(Client, on_delete=CASCADE, related_name='received_messages')

    async def update_status(self, new_status: MessageStatus):
        self.status = new_status
        await self.save()

mailing/forms.py
from django.forms import ModelForm

from .models import Mailing


class MailingForm(ModelForm):
    class Meta:
        model = Mailing
        fields = [
            'start_time',
            'text',
            'codes_filter',
            'tags_filter',
            'end_time',
        ]

mailing/views.py
from datetime import datetime

from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render, redirect, get_object_or_404
import pytz
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

import notification_service.settings
import stats.views
from clients.models import Client
from notification_service.views import login_required
from .forms import MailingForm
from .models import Mailing, Message, MessageStatus
from .serializers import MailingSerializer
from .tasks import send_mail_task


def get_mailings_and_stats():
    previous_mailings = Mailing.get_previous_mailings().order_by('id')
    current_mailings = Mailing.get_current_mailings().order_by('id')
    future_mailings = Mailing.get_future_mailings().order_by('id')

    previous_messages = {mailing.id: stats.views.get_messages_stats(mailing=mailing.id) for mailing in
                         previous_mailings}
    current_messages = {mailing.id: stats.views.get_messages_stats(mailing=mailing.id) for mailing in
                        current_mailings}
    future_messages = {mailing.id: stats.views.get_messages_stats(mailing=mailing.id) for mailing in future_mailings}

    return {
        'previous_mailings': Mailing.get_previous_mailings(),
        'current_mailings': Mailing.get_current_mailings(),
        'future_mailings': Mailing.get_future_mailings(),

        'previous_messages': previous_messages,
        'current_messages': current_messages,
        'future_messages': future_messages
    }


@login_required
def mailing(request: WSGIRequest):
    # generate()
    return render(request, "mailing/mailing.html", context=get_mailings_and_stats())


# add mailing

def create_mailing_util(data):
    form = MailingForm(data)
    validate_form(form)
    new_mailing = form.save()
    create_messages(new_mailing)
    return new_mailing


@login_required
def create_mailing(request: WSGIRequest):
    if request.method == 'GET':
        return render(request, "mailing/add_mailing.html", {'form': MailingForm})
    elif request.method == 'POST':
        try:
            create_mailing_util(request.POST)
            return redirect('mailing:mailing')
        except ValueError as e:
            return render(request, 'mailing/add_mailing.html',
                          {'form': MailingForm(request.POST), 'error': e})


@api_view(['POST'])
def create_mailing_api(request):
    try:
        new_mailing = create_mailing_util(request.data)
        serializer = MailingSerializer(new_mailing)
        return Response(serializer.data, status=status.HTTP_201_CREATED)
    except ValueError as e:
        return Response({"error": str(e)}, status=status.HTTP_400_BAD_REQUEST)


# update mailing


def update_mailing_util(form: MailingForm, mailing_id: int):
    old_mailing = get_object_or_404(Mailing, pk=mailing_id)
    new_mailing = validate_form(form)
    form.save(commit=False)
    time_changed = old_mailing.end_time != new_mailing.end_time or old_mailing.start_time != new_mailing.start_time
    filters_changed = old_mailing.tags_filter != new_mailing.tags_filter or old_mailing.codes_filter != new_mailing.codes_filter
    form.save()
    if time_changed or filters_changed:
        update_messages(new_mailing, time_changed=time_changed, filters_changed=filters_changed)


@login_required
def update_mailing(request: WSGIRequest, mailing_id: int):
    mailing_to_edit = get_object_or_404(Mailing, pk=mailing_id)
    if request.method == 'POST':
        try:
            update_mailing_util(MailingForm(request.POST, instance=mailing_to_edit), mailing_id)
            return redirect('mailing:mailing')
        except ValueError as e:
            return render(request, 'mailing/add_mailing.html',
                          {'form': MailingForm(request.POST), 'error': e})
    else:
        form = MailingForm(instance=mailing_to_edit)
    return render(request, 'mailing/add_mailing.html', {'form': form, 'mailing': mailing_to_edit})


@api_view(['PATCH'])
def update_mailing_api(request, mailing_id: int):
    mailing_to_update = get_object_or_404(Mailing, pk=mailing_id)
    try:
        old_data = MailingSerializer(mailing_to_update).data
        new_data = {**old_data, **request.data}
        update_mailing_util(MailingForm(new_data, instance=mailing_to_update), mailing_id)
    except ValueError as e:
        return Response({'error': str(e)}, status=status.HTTP_400_BAD_REQUEST)
    return Response(status=status.HTTP_200_OK)


# delete mailing

def delete_mailing_util(mailing: Mailing):
    mailing.delete()


@login_required
def delete_mailing(request: WSGIRequest, mailing_id: int):
    mailing_to_delete = get_object_or_404(Mailing, pk=mailing_id)
    try:
        if request.method == 'POST':
            delete_mailing_util(mailing_to_delete)
    except Exception as e:
        return render(request, 'mailing/mailing.html', {'error': 'Cannot delete mailing: ' + str(e)})
    return redirect('mailing:mailing')


@api_view(['DELETE'])
def delete_mailing_api(request, mailing_id: int):
    mailing_to_delete = get_object_or_404(Mailing, pk=mailing_id)
    try:
        delete_mailing_util(mailing_to_delete)
    except Exception as e:
        return Response({'error': 'Cannot delete mailing: ' + str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
    return Response(status=status.HTTP_200_OK)


# utils

def eval_time(start_time, timezone):
    return start_time.astimezone(pytz.timezone(timezone))


def create_messages(mailing: Mailing):
    clients = Client.get_clients_by_tags_and_codes(tags=mailing.tags_filter, codes=mailing.codes_filter)
    for client in clients:
        message = Message.objects.create(mailing=mailing, client=client)
        send_time = eval_time(mailing.start_time, client.timezone)
        add_to_queue(message.id, send_time)


def add_to_queue(message_id: int, send_time) -> None:
    now = datetime.now(pytz.timezone(notification_service.settings.TIME_ZONE))
    if send_time < now:
        send_mail_task.apply_async(args=[message_id])
    else:
        send_mail_task.apply_async(args=[message_id], eta=send_time)


def validate_form(form: MailingForm):
    if not form.is_valid():
        raise ValueError(form.errors)
    new_mailing = form.save(commit=False)
    if new_mailing.end_time < datetime.now(pytz.timezone(notification_service.settings.TIME_ZONE)):
        raise ValueError("End time is in the past")
    if new_mailing.end_time < new_mailing.start_time:
        raise ValueError("End time is before start time")
    return new_mailing


def update_messages(mailing: Mailing, time_changed: bool, filters_changed: bool):
    messages = list(Message.objects.filter(mailing=mailing.id,
                                           status__in=[MessageStatus.WAITING, MessageStatus.FAILED_WAITING,
                                                       MessageStatus.FAILED]).all())
    clients = {message.client for message in messages}
    if filters_changed:
        additional_clients = [i for i in
                              Client.get_clients_by_tags_and_codes(tags=mailing.tags_filter, codes=mailing.codes_filter)
                              if i not in clients]
        for client in additional_clients:
            message = Message.objects.create(mailing=mailing, client=client)
            messages.append(message)

    if time_changed:
        for message in messages:
            send_time = eval_time(mailing.start_time, message.client.timezone)
            add_to_queue(message.id, send_time)

mailing/templates/mailing/add_mailing.html
<!-- add_project.html -->

<!DOCTYPE html>
<html lang="en">
{% csrf_token %}

<head>
    <meta charset="UTF-8">
    <title>Add new mailing</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        .error-message {
            color: red;
            text-align: center;
            width: 400px; /* Match the form width */
            margin-bottom: 20px;
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 400px;
            width: 100%;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        h1 {
            text-align: center;
            color: #333;
        }

        label {
            display: block;
            margin-bottom: 8px;
            width: 100%;
        }

        input,
        select,
        textarea {
            width: calc(100% - 16px);
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        textarea {
            width: 100%; /* 100% width */
            min-width: calc(100% - 16px); /* Min width excluding padding */
            max-width: calc(100% - 16px); /* Max width excluding padding */
            height: 80px; /* Initial height */
            min-height: 80px; /* Min height */
            max-height: 200px; /* Max height */
            resize: vertical; /* Allow vertical resizing */
        }

        button {
            background-color: #007bff;
            color: #fff;
            padding: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
        }

        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>

<body>
{% if error %}
    <h1>
        <div class="error-message">{{ error }}</div>
    </h1>
{% endif %}

<form method="POST">
    {% csrf_token %}
    {% if mailing %}
        <h1>Редактировать рассылку</h1>
    {% else %}
        <h1>Новая рассылка</h1>
    {% endif %}

    <label for="text">Текст рассылки</label>
    {{ form.text }}

    <label for="start_time" id="start_time">Время начала рассылки</label>
    <input type="datetime-local" id="start_time" value="{{ mailing.start_time|date:'Y-m-d\TH:i' }}" name="start_time">

    <label for="end_time" id="end_time">Время окончания рассылки</label>
    <input type="datetime-local" id="end_time" value="{{ mailing.end_time|date:'Y-m-d\TH:i' }}" name="end_time">

    <label for="codes_filter">Фильтр: допустимые коды операторов (Перечислите через запятую)</label>
    <input id="codes_filter" name="codes_filter" value="{{ mailing.codes_filter|join:', ' }}"
           placeholder="910, 810, 880"></input>

    <label for="tags_filter">Фильтр: допустимые теги клиенты (Перечислите через запятую)</label>
    <input id="tags_filter" name="tags_filter" value="{{ mailing.tags_filter|join:', ' }}"></input>

    {% if mailing %}
        <button type="submit">Сохранить</button>
    {% else %}
        <button type="submit">Добавить</button>
    {% endif %}

</form>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const codesInput = document.getElementById('codes_filter');
        const tagsInput = document.getElementById('tags_filter');
        const warningMessage1 = document.createElement('div');
        warningMessage1.style.color = 'red';
        const warningMessage2 = document.createElement('div');
        warningMessage2.style.color = 'red';
        codesInput.parentNode.insertBefore(warningMessage1, codesInput.previousSibling);
        tagsInput.parentNode.insertBefore(warningMessage2, tagsInput.previousSibling);

        codesInput.addEventListener('input', function () {
            const regex = /^(\d{3}(,\s\d{3})*)?$/;
            if (regex.test(codesInput.value)) {
                warningMessage1.textContent = '';
            } else {
                warningMessage1.textContent = 'Формат не соответствует. Допустимые значения: пустое поле или 3-х значные числа через запятую и пробел.';
            }
        });

        tagsInput.addEventListener('input', function () {
            const regex = /^(([a-zA-Z]*)(,\s[a-zA-Z]+)*)?$/;
            if (regex.test(tagsInput.value)) {
                warningMessage2.textContent = '';
            } else {
                warningMessage2.textContent = 'Формат не соответствует. Допустимые значения: теги на английском языке через запятую и пробел.';
            }
        })
    });

    document.querySelector('form').addEventListener('submit', function (e) {
        const codesFilterInput = document.getElementById('codes_filter');
        const tagsFilterInput = document.getElementById('tags_filter');
        const codesFilterValue = codesFilterInput.value;
        const tagsFilterValue = tagsFilterInput.value;
        if ((!codesFilterValue || codesFilterValue.match(/^(\d{3}(,\s\d{3})*)?$/)) &&
            (!tagsFilterValue || tagsFilterValue.match(/^(([a-zA-Z]*)(,\s[a-zA-Z]+)*)?$/))) {
            return true;
        } else {
            e.preventDefault();
            alert('Формат не соответствует требуемому.');
            return false;
        }
    });
</script>


</body>

</html>

mailing/templates/mailing/mailing.html
{% extends 'notification_service/base.html' %}

<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f4f7f6;
        color: #333;
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        flex-direction: column;
    }
</style>

{% load my_filters %}

{% block content %}
    <header>
        <h1>Система Управления Рассылками</h1>
        <a class="auth-button" href="{% url 'logout' %}">Logout</a>
    </header>
    <div class="content">

        <div class="block">
            <h2>Будущие рассылки</h2>
            <p><a class="add-button" href="{% url 'mailing:create_mailing' %}">Добавить рассылку</a></p>
            {% for mailing in future_mailings %}
                <div class="future-mailing-item{% if forloop.counter > 3 %} hidden{% endif %}">
                    <h3>Рассылка №{{ mailing.id }}</h3>
                    <p>Текст рассылки: {{ mailing.text|truncatechars:50 }}</p>
                    <p>Начало рассылки: {{ mailing.start_time }}</p>
                    <p>Окончание рассылки: {{ mailing.end_time }}</p>
                    {% if mailing.codes_filter %}
                        <p>Фильтр по кодам: {{ mailing.codes_filter }}</p>
                    {% endif %}
                    {% if mailing.tags_filter %}
                        <p>Фильтр по тэгам: {{ mailing.tags_filter }}</p>
                    {% endif %}
                    <div>Статистика:</div>
                    <p>Успешно
                        отправлены: {{ future_messages|get_msgs_stats_for_mailing:mailing|get_spec_msgs_stats:"sent_messages" }}
                        сообщений</p>
                    <p>Не отправлены и уже не
                        будут: {{ future_messages|get_msgs_stats_for_mailing:mailing|get_spec_msgs_stats:"failed_messages" }}
                        сообщений</p>
                    <p>Ожидают
                        отправки: {{ future_messages|get_msgs_stats_for_mailing:mailing|get_spec_msgs_stats:"waiting_messages" }}
                        сообщений</p>
                    <p>Ожидают повторной
                        отправки: {{ future_messages|get_msgs_stats_for_mailing:mailing|get_spec_msgs_stats:"failed_waiting_messages" }}
                        сообщений</p>
                    <div class="buttons">
                        <a class="edit-button" href="{% url 'mailing:update_mailing' mailing.id %}">Редактировать</a>
                        <form method="POST" action="{% url 'mailing:delete_mailing' mailing.id %}">
                            {% csrf_token %}
                            <button type="submit" class="delete-button">Удалить</button>
                        </form>
                    </div>
                </div>
            {% endfor %}
            {% if future_mailings|length > 3 %}
                <a href="#" class="show-more-button" id="show-more-future">Показать больше</a>
            {% endif %}
        </div>

        <div class="block">
            <h2>Текущие рассылки</h2>
            {% for mailing in current_mailings %}
                <div class="current-mailing-item{% if forloop.counter > 3 %} hidden{% endif %}">
                    <h3>Рассылка №{{ mailing.id }}</h3>
                    <p>Текст рассылки: {{ mailing.text|truncatechars:50 }}</p>
                    <p>Начало рассылки: {{ mailing.start_time }}</p>
                    <p>Окончание рассылки: {{ mailing.end_time }}</p>
                    {% if mailing.codes_filter %}
                        <p>Фильтр по кодам: {{ mailing.codes_filter }}</p>
                    {% endif %}
                    {% if mailing.tags_filter %}
                        <p>Фильтр по тэгам: {{ mailing.tags_filter }}</p>
                    {% endif %}
                    <div>Статистика:</div>
                    <p>Успешно
                        отправлены: {{ current_messages|get_msgs_stats_for_mailing:mailing|get_spec_msgs_stats:"sent_messages" }}
                        сообщений</p>
                    <p>Не отправлены и уже не
                        будут: {{ current_messages|get_msgs_stats_for_mailing:mailing|get_spec_msgs_stats:"failed_messages" }}
                        сообщений</p>
                    <p>Ожидают
                        отправки: {{ current_messages|get_msgs_stats_for_mailing:mailing|get_spec_msgs_stats:"waiting_messages" }}
                        сообщений</p>
                    <p>Ожидают повторной
                        отправки: {{ current_messages|get_msgs_stats_for_mailing:mailing|get_spec_msgs_stats:"failed_waiting_messages" }}
                        сообщений</p>
                    <div class="buttons">
                        <a class="edit-button" href="{% url 'mailing:update_mailing' mailing.id %}">Редактировать</a>
                        <form method="POST" action="{% url 'mailing:delete_mailing' mailing.id %}">
                            {% csrf_token %}
                            <button type="submit" class="delete-button">Удалить</button>
                        </form>
                    </div>
                </div>
            {% endfor %}
            {% if current_mailings|length > 3 %}
                <a href="#" class="show-more-button" id="show-more-current">Показать больше</a>
            {% endif %}
        </div>

        <div class="block">
            <h2>Завершенные рассылки</h2>
            {% for mailing in previous_mailings %}
                <div class="previous-mailing-item{% if forloop.counter > 3 %} hidden{% endif %}">
                    <h3>Рассылка №{{ mailing.id }}</h3>
                    <p>Текст рассылки: {{ mailing.text|truncatechars:50 }}</p>
                    <p>Начало рассылки: {{ mailing.start_time }}</p>
                    <p>Окончание рассылки: {{ mailing.end_time }}</p>
                    {% if mailing.codes_filter %}
                        <p>Фильтр по кодам: {{ mailing.codes_filter }}</p>
                    {% endif %}
                    {% if mailing.tags_filter %}
                        <p>Фильтр по тэгам: {{ mailing.tags_filter }}</p>
                    {% endif %}
                    <div>Статистика:</div>
                    <p>Успешно
                        отправлены: {{ previous_messages|get_msgs_stats_for_mailing:mailing|get_spec_msgs_stats:"sent_messages" }}
                        сообщений</p>
                    <p>Не отправлены и уже не
                        будут: {{ previous_messages|get_msgs_stats_for_mailing:mailing|get_spec_msgs_stats:"failed_messages" }}
                        сообщений</p>
                    <p>Ожидают
                        отправки: {{ previous_messages|get_msgs_stats_for_mailing:mailing|get_spec_msgs_stats:"waiting_messages" }}
                        сообщений</p>
                    <p>Ожидают повторной
                        отправки: {{ previous_messages|get_msgs_stats_for_mailing:mailing|get_spec_msgs_stats:"failed_waiting_messages" }}
                        сообщений</p>
                    <div class="buttons">
                        <form method="POST" action="{% url 'mailing:delete_mailing' mailing.id %}">
                            {% csrf_token %}
                            <button type="submit" class="delete-button">Удалить</button>
                        </form>
                    </div>
                </div>
            {% endfor %}
            {% if previous_mailings|length > 3 %}
                <a href="#" class="show-more-button" id="show-more-previous">Показать больше</a>
            {% endif %}
        </div>

    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            function showAllMailings(buttonId, itemsClass) {
                const button = document.getElementById(buttonId);
                button.addEventListener('click', function (e) {
                    e.preventDefault();
                    const items = document.querySelectorAll('.' + itemsClass);
                    items.forEach(function (item) {
                        item.classList.remove('hidden');
                    });
                    button.style.display = 'none';
                });
            }

            if (document.querySelectorAll('.future-mailing-item').length > 3) {
                showAllMailings('show-more-future', 'future-mailing-item')
            }
            if (document.querySelectorAll('.current-mailing-item').length > 3) {
                showAllMailings('show-more-current', 'current-mailing-item')
            }
            if (document.querySelectorAll('.previous-mailing-item').length > 3) {
                showAllMailings('show-more-previous', 'previous-mailing-item')
            }
        });
    </script>

{% endblock %}