clients/urls.py
from django.urls import path

from clients import views

app_name = 'clients'

urlpatterns = [
    path("", views.clients, name="clients"),
    path('create_client/', views.create_client, name='add_client'),
    path('update_client/<int:client_id>', views.update_client, name='update_client'),
    path('delete_client/<int:client_id>', views.delete_client, name='delete_client'),

    path('create/', views.create_client_api, name='create_client_api'),
    path('delete/<int:client_id>', views.delete_client_api, name='delete_client_api'),
    path('update/<int:client_id>', views.update_client_api, name='update_client_api'),
]

mailing/urls.py
from django.urls import path

from mailing import views

app_name = 'mailing'

urlpatterns = [
    path("", views.mailing, name="mailing"),
    path('create_mailing/', views.create_mailing, name='create_mailing'),
    path('update_mailing/<int:mailing_id>', views.update_mailing, name='update_mailing'),
    path('delete_mailing/<int:mailing_id>', views.delete_mailing, name='delete_mailing'),

    path('create/', views.create_mailing_api, name='create_mailing_api'),
    path('delete/<int:mailing_id>', views.delete_mailing_api, name='delete_mailing_api'),
    path('update/<int:mailing_id>', views.update_mailing_api, name='update_mailing_api'),
]

notification_service/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include

from notification_service import views

app_name = 'notification_service'

urlpatterns = [
    path("admin/", admin.site.urls),

    # auth
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path("callback", views.callback, name="callback"),

    path("", views.home, name="home"),
    path('mailing/', include('mailing.urls')),
    path('clients/', include('clients.urls')),
    path('stats/', include('stats.urls')),

]

stats/urls.py
from django.urls import path

from stats import views

app_name = 'stats'

urlpatterns = [
    path('', views.get_common_stats_api, name='get_common_stats_api'),
    path('<int:mailing_id>', views.get_spec_stats_api, name='get_spec_stats_api'),
]

notification_service/views.py
import json
from authlib.integrations.django_client import OAuth
from django.conf import settings
from django.shortcuts import redirect, render, redirect
from urllib.parse import quote_plus, urlencode
from functools import wraps
from django.http import HttpResponseRedirect
from django.urls import reverse

from clients.models import Client
from mailing.models import Mailing
from stats.views import get_messages_stats

oauth = OAuth()

oauth.register(
    "auth0",
    client_id=settings.AUTH0_CLIENT_ID,
    client_secret=settings.AUTH0_CLIENT_SECRET,
    client_kwargs={
        "scope": "openid profile email",
    },
    server_metadata_url=f"https://{settings.AUTH0_DOMAIN}/.well-known/openid-configuration",
)


def login_required(f):
    @wraps(f)
    def wrap(request, *args, **kwargs):
        if "user" not in request.session:
            return HttpResponseRedirect(reverse('login'))
        return f(request, *args, **kwargs)

    return wrap


def home(request):
    return render(
        request,
        "notification_service/home.html",
        context={
            "session": request.session.get("user"),
            "pretty": json.dumps(request.session.get("user"), indent=4),
            "messages": get_messages_stats(),
            "clients_num": len(Client.objects.all()),
            "mailing_num": len(Mailing.objects.all())
        },
    )


def callback(request):
    token = oauth.auth0.authorize_access_token(request)
    request.session["user"] = token
    return redirect(request.build_absolute_uri(reverse("home")))


def login(request):
    return oauth.auth0.authorize_redirect(
        request, request.build_absolute_uri(reverse("callback"))
    )


def logout(request):
    request.session.clear()

    return redirect(
        f"https://{settings.AUTH0_DOMAIN}/v2/logout?"
        + urlencode(
            {
                "returnTo": request.build_absolute_uri(reverse("home")),
                "client_id": settings.AUTH0_CLIENT_ID,
            },
            quote_via=quote_plus,
        ),
    )

notification_service/templates/notification_service/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Управление Рассылками{% endblock %}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f4f7f6;
            color: #333;
        }

        .menu {
            margin-bottom: 20px;
            padding: 10px;
            background-color: #e3e8e8;
        }

        .menu a {
            text-decoration: none;
            margin-right: 15px;
            color: #0056b3;
            font-weight: bold;
        }

        .menu a:hover {
            color: #023e8a;
        }

        .content h2 {
            color: #023e8a;
        }

        .block h2 {
            color: #023e8a;
        }

        .block div {
            padding: 5px;
            margin-bottom: 7px;
            background-color: #e3e8e8;
            border-radius: 5px;
        }

        .block div h3 {
            color: #007bff;
            margin-left: 10px;
        }

        .block div p {
            margin-left: 20px;
            font-size: 14px;
        }

        .content {
            width: 80%;
            max-width: 800px;
            background-color: #ffffff;
            padding: 20px;
            margin: 20px 0;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .block {
            margin-bottom: 30px;
            border-left: 4px solid #007bff;
            padding-left: 15px;
        }

        .block h2 {
            color: #023e8a;
        }

        .block div {
            padding: 5px;
            margin-bottom: 7px;
            background-color: #e3e8e8;
            border-radius: 5px;
        }

        .block div h3 {
            color: #007bff;
            margin-left: 10px;
        }

        .block div p {
            margin-left: 20px;
            font-size: 14px;
        }

        .delete-button,
        .edit-button,
        .add-button {
            background-color: #007bff;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            text-decoration: none;
            font-size: 16px;
        }

        .delete-button,
        .edit-button {
            font-size: 10px
        }


        .edit-button:hover,
        .add-button:hover {
            background-color: #0056b3;
        }

        .buttons {
            display: flex;
            justify-content: flex-start;
            margin-left: 5px;
            gap: 5px;
        }

        .delete-button {
            background-color: #dc3545;
        }

        .delete-button:hover {
            background-color: #c82333;
        }


        .hidden {
            display: none;
        }

        .show-more-button {
            display: block;
            background-color: #007bff;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            text-align: center;
            margin: 10px 0;
            transition: background-color 0.3s;
        }

        .show-more-button:hover {
            background-color: #0056b3;
        }

        .auth-button {
            background-color: #007bff;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            text-decoration: none;
            position: absolute;
            right: 20px;
            top: 20px;
        }
    </style>
</head>
<body>
<header>
    <nav class="menu">
        <a href="{% url 'home' %}">Домашняя страница</a>
        <a href="{% url 'mailing:mailing' %}">Рассылки</a>
        <a href="{% url 'clients:clients' %}">Клиенты</a>
    </nav>
</header>

{% block content %}{% endblock %}

</body>
</html>

notification_service/templates/notification_service/home.html
{% extends 'notification_service/base.html' %}
{% load my_filters %}


{% block content %}
    <header>
        <h1>Система Управления Рассылками</h1>
        {% if session.userinfo.name %}
            <a class="auth-button" href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a class="auth-button" href="{% url 'login' %}">Login</a>
        {% endif %}
    </header>
    <section class="content" id="create-mailing">
        <h2>Рассылки</h2>
        {% if not session.userinfo.name %}
            <p>Для просмотра рассылок необходимо авторизоваться как администратор</p>
        {% else %}
            <p>Всего рассылок: {{ mailing_num }}</p>
            <p>Перейдите на страницу "Рассылки" для более подробной информации</p>
        {% endif %}
    </section>
    <section class="content" id="view-clients">
        <h2>Клиенты</h2>
        {% if not session.userinfo.name %}
            <p>Для просмотра клиентов необходимо авторизоваться как администратор</p>
        {% else %}
            <p>Всего клиентов: {{ clients_num }}</p>
            <p>Перейдите на страницу "Клиенты" для более подробной информации</p>
        {% endif %}
    </section>
    <section class="content" id="collect-stats">
        <h2>Статистика</h2>
        {% if not session.userinfo.name %}
            <p>Для просмотра статистики необходимо авторизоваться как администратор</p>
        {% else %}
            <p>Успешно отправлено: {{ messages|get_spec_msgs_stats:"sent_messages" }}</p>
            <p>Не отправлены и уже не будут: {{ messages|get_spec_msgs_stats:"failed_messages" }} сообщений</p>
            <p>Ожидают отправки: {{ messages|get_spec_msgs_stats:"waiting_messages" }} сообщений</p>
            <p>Ожидают повторной отправки: {{ messages|get_spec_msgs_stats:"failed_waiting_messages" }} сообщений</p>
        {% endif %}
    </section>
{% endblock %}