clients/urls.py
from django.urls import path

from clients import views

app_name = 'clients'

urlpatterns = [
    path("", views.clients, name="clients"),
    path('create_client/', views.create_client, name='add_client'),
    path('update_client/<int:client_id>', views.update_client, name='update_client'),
    path('delete_client/<int:client_id>', views.delete_client, name='delete_client'),

    path('create/', views.create_client_api, name='create_client_api'),
    path('delete/<int:client_id>', views.delete_client_api, name='delete_client_api'),
    path('update/<int:client_id>', views.update_client_api, name='update_client_api'),
]

notification_service/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include

from notification_service import views

app_name = 'notification_service'

urlpatterns = [
    path("admin/", admin.site.urls),

    # auth
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path("callback", views.callback, name="callback"),

    path("", views.home, name="home"),
    path('mailing/', include('mailing.urls')),
    path('clients/', include('clients.urls')),
    path('stats/', include('stats.urls')),

]

stats/urls.py
from django.urls import path

from stats import views

app_name = 'stats'

urlpatterns = [
    path('', views.get_common_stats_api, name='get_common_stats_api'),
    path('<int:mailing_id>', views.get_spec_stats_api, name='get_spec_stats_api'),
]

clients/models.py
from django.db import models
import pytz

TIMEZONE_CHOICES = [(tz, tz) for tz in pytz.all_timezones]


class Client(models.Model):
    phone_number = models.PositiveBigIntegerField(blank=False, null=False)
    operator_code = models.IntegerField(blank=False, null=False)
    tag = models.CharField(blank=True, null=True, max_length=150)
    timezone = models.CharField(blank=False, null=False, max_length=100, choices=TIMEZONE_CHOICES,
                                default='UTC')

    @classmethod
    def get_clients_by_tags_and_codes(cls, tags: list[str], codes: list[int]):
        if not tags and not codes:
            return cls.objects.all()
        if not tags:
            return cls.objects.filter(operator_code__in=codes)
        if not codes:
            return cls.objects.filter(tag__in=tags)
        return cls.objects.filter(tag__in=tags, operator_code__in=codes)

clients/forms.py
from django.forms import ModelForm, Select

from . import models
from .models import Client


class ClientForm(ModelForm):
    class Meta:
        model = Client
        fields = [
            'phone_number',
            'tag',
            'timezone'
        ]
        widgets = {
            'timezone': Select(choices=models.TIMEZONE_CHOICES)
        }

clients/views.py
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render, redirect, get_object_or_404
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from notification_service.views import login_required
from .forms import ClientForm
from .models import Client
from .serializers import ClientSerializer


@login_required
def clients(request):
    return render(request, "clients/clients.html", {
        'clients': Client.objects.all().order_by('id')
    })


# create client

def create_client_util(data):
    form = ClientForm(data)
    new_client = validate_and_save(form)
    return new_client


@login_required
def create_client(request):
    if request.method == 'GET':
        return render(request, "clients/add_client.html", {'form': ClientForm})
    elif request.method == 'POST':
        try:
            create_client_util(request.POST)
            return redirect('clients:clients')
        except ValueError as e:
            return render(request, 'clients/add_client.html',
                          {'form': ClientForm(request.POST), 'error': e})


@api_view(['POST'])
def create_client_api(request):
    try:
        new_client = create_client_util(request.data)
    except ValueError as e:
        return Response({"error": str(e)}, status=status.HTTP_400_BAD_REQUEST)
    serializer = ClientSerializer(new_client)
    return Response(serializer.data, status=status.HTTP_201_CREATED)


# update client

def update_client_util(form: ClientForm, client_id: int):
    get_object_or_404(Client, pk=client_id)
    validate_and_save(form)


@login_required
def update_client(request: WSGIRequest, client_id: int):
    client_to_edit = get_object_or_404(Client, pk=client_id)
    if request.method == 'POST':
        try:
            update_client_util(ClientForm(request.POST, instance=client_to_edit), client_id)
            return redirect('clients:clients')
        except ValueError as e:
            return render(request, 'clients/add_client.html',
                          {'form': ClientForm(request.POST), 'error': e})
    else:
        form = ClientForm(instance=client_to_edit)
    return render(request, 'clients/add_client.html', {'form': form, 'client': client_to_edit})


@api_view(['PATCH'])
def update_client_api(request, client_id: int):
    client_to_edit = get_object_or_404(Client, pk=client_id)
    try:
        old_data = ClientSerializer(client_to_edit).data
        new_data = {**old_data, **request.data}
        update_client_util(ClientForm(new_data, instance=client_to_edit), client_id)
    except ValueError as e:
        return Response({'error': str(e)}, status=status.HTTP_400_BAD_REQUEST)
    return Response(status=status.HTTP_200_OK)


# delete client

def delete_client_util(client: Client):
    client.delete()


@login_required
def delete_client(request, client_id: int):
    client = get_object_or_404(Client, pk=client_id)
    try:
        delete_client_util(client)
    except Exception as e:
        return render(request, 'clients/clients.html', {'error': str(e)})
    return redirect('clients:clients')


@api_view(['DELETE'])
def delete_client_api(request, client_id: int):
    client = get_object_or_404(Client, pk=client_id)
    try:
        delete_client_util(client)
    except Exception as e:
        return Response({'error': str(e)}, status=status.HTTP_404_NOT_FOUND)
    return Response(status=status.HTTP_200_OK)


def validate_and_save(form: ClientForm) -> Client:
    if not form.is_valid():
        raise ValueError(form.errors)
    new_client = form.save(commit=False)
    phone_str = str(new_client.phone_number)
    if len(phone_str) != 10:
        raise ValueError("Неверный номер телефона")

    operator_code = int(phone_str[:3])
    new_client.operator_code = operator_code
    new_client.phone_number = int('7' + phone_str)
    new_client.save()
    return new_client

clients/templates/clients/add_client.html
<!-- add_project.html -->

<!DOCTYPE html>
<html lang="en">
{% csrf_token %}

<head>
    <meta charset="UTF-8">
    <title>Add new client</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        .error-message {
            color: red;
            text-align: center;
            width: 400px;
            margin-bottom: 20px;
        }

        form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 400px;
            width: 100%;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        h1 {
            text-align: center;
            color: #333;
        }

        label {
            display: block;
            margin-bottom: 8px;
            width: 100%;
        }

        input,
        select,
        textarea {
            width: calc(100% - 16px);
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        textarea {
            width: 100%;
            min-width: calc(100% - 16px);
            max-width: calc(100% - 16px);
            height: 80px;
            min-height: 80px;
            max-height: 200px;
            resize: vertical;
        }

        button {
            background-color: #007bff;
            color: #fff;
            padding: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
        }

        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>

<body>
{% if error %}
    <h1>
        <div class="error-message">{{ error }}</div>
    </h1>
{% endif %}

<form method="POST">
    {% csrf_token %}
    {% if client %}
        <h1>Редактировать Клиента</h1>
    {% else %}
        <h1>Новый Клиент</h1>
    {% endif %}

    <label for="phone_number">Номер Телефона (без кода страны)</label>
    <input id="phone_number" name="phone_number" value="{{ client.phone_number|stringformat:"s"|slice:"1:" }}" placeholder="9101459029">

    <label for="tag">Тэг</label>
    {{ form.tag }}

    <label for="timezone">Часовой пояс</label>
    {{ form.timezone }}

    <button type="submit">Добавить</button>


</form>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const phone_input = document.getElementById('phone_number');
        const warningMessage = document.createElement('div');
        warningMessage.style.color = 'red';
        warningMessage.style.marginBottom = '5px';
        phone_input.parentNode.insertBefore(warningMessage, phone_input.nextSibling);

        phone_input.addEventListener('input', function () {
            const regex = /^(\d{10})?$/;
            if (regex.test(phone_input.value)) {
                warningMessage.textContent = '';
            } else {
                warningMessage.textContent = 'Формат не соответствует. Формат: 10 цифр';
            }
        });

    });

    document.querySelector('form').addEventListener('submit', function (e) {
        const phoneNumberInput = document.getElementById('phone_number');
        const codesFilterValue = phoneNumberInput.value;
        if (codesFilterValue.match(/^\d{10}$/)) {
            return true;
        } else {
            e.preventDefault();
            alert('Формат не соответствует требуемому.');
            return false;
        }
    });
</script>
</body>
</html>

clients/templates/clients/clients.html
{% extends 'notification_service/base.html' %}
<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f4f7f6;
        color: #333;
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        flex-direction: column;
    }
</style>

{% block content %}
    <header>
        <h1>Система Управления Рассылками</h1>
        <a class="auth-button" href="{% url 'logout' %}">Logout</a>
    </header>
    <div class="content">
        <div class="block">
            <h2>Клиенты</h2>
            <p><a class="add-button" href="{% url 'clients:add_client' %}">Добавить клиента</a></p>
            {% for client in clients %}
                <div class="client-item{% if forloop.counter > 3 %} hidden{% endif %}">
                    <h3>Клиент №{{ client.id }}</h3>
                    <p>Номер телефона: {{ client.phone_number }}</p>
                    <p>Код оператора: {{ client.operator_code }}</p>
                    <p>Тэг: {{ client.tag }}</p>
                    <div class="buttons">
                        <a class="edit-button" href="{% url 'clients:update_client' client.id %}">Редактировать</a>
                        <form method="POST" action="{% url 'clients:delete_client' client.id %}">
                            {% csrf_token %}
                            <button type="submit" class="delete-button">Удалить</button>
                        </form>
                    </div>
                </div>
            {% endfor %}
            {% if clients|length > 3 %}
                <a href="#" class="show-more-button" id="show-more">Показать больше</a>
            {% endif %}
        </div>

    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            function showAllMailings(buttonId, itemsClass) {
                const button = document.getElementById(buttonId);
                button.addEventListener('click', function (e) {
                    e.preventDefault();
                    const items = document.querySelectorAll('.' + itemsClass);
                    items.forEach(function (item) {
                        item.classList.remove('hidden');
                    });
                    button.style.display = 'none';
                });
            }

            showAllMailings('show-more', 'client-item')
        });
    </script>
{% endblock %}